sudo: required
services:
  - docker

before_install:
  - docker build -t aqeelraza12/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aqeelraza12/docker-react npm run test -- --coverage